### ISSUE TITLE
Add README and further info

### ISSUE THREAD

**Issue by matt-paul** [recyclerapp/recyclerapp.github.io#2]
Hey there!

I just came across your post on Hacker News

```
As a first year CS student,i created https://recyclair.eu.org/ It's a website to find the nearest garbage or recycling bin so you never have the excuse to throw it on the ground.It's completely open source https://github.com/recyclerapp/recyclair . It currently relies on community contribution so any help is appreciated.
```

Great stuff, please add some further information such as a README and perhaps create some issues for context and so that other people can easily see if they might be able to help you.

Also, come and shout about your project in the climateaction.tech slack group!

Best,

Matt

**Comment by AlexTselikas** [comment]
Hi Matt,
Thank you for your suggestions!The project now has a README file.
Will hop on the slack group for sure!
Thanks,
Alex
